name: Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t edugonzalezdocker/gitrepo:latest  .

      - name: Login DockerHub
        run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: docker push EduGonzalez/gitrepo:latest
